application: flashcardsforglass
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/images/flashcardsforglass-icon-128x128.png
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: django
  version: "1.5"
